# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jinhwan's Blog
email: jhbae200@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  생각하자
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jhbae200.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jhbae200
facebook_username: jhbae200
# Build settings
markdown: kramdown
theme: minima
paginate: 7
tag_build: true
safe: true
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
timezone: Asia/Seoul
permalink: /:year/:month/:day/:title/
asset_url: /assets
keep_files: ["assets", "files"]
